### ISSUE TITLE
Cannot Use Along with Stackblur

### ISSUE THREAD

**Issue by victorguilhermeo** [daimajia/AndroidViewHover#15]
The title explain itself, this library cannot be used along with stackblur, because of a "duplicated renderscript error"
Follows the log:

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	C:\Users\Wiloo\AppData\Local\Android\sdk\build-tools\21.1.2\dx.bat --dex --no-optimize --output C:\Users\Wiloo\AndroidStudioProjects\ProtoFragment\app\build\intermediates\dex\debug --input-list=C:\Users\Wiloo\AndroidStudioProjects\ProtoFragment\app\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
	2
Output:
	UNEXPECTED TOP-LEVEL EXCEPTION:
	com.android.dex.DexException: Multiple dex files define Landroid/support/v8/renderscript/Allocation$1;
		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)

Once the line compile project(':StackBlur') is removed from the build.gradle the project works just fine. Any idea why this is happening?

**Comment by daimajia** [comment]
One simple solution:
1. Git clone this project
2. Remove render script settings from gradle file

try to compile it.
