### ISSUE TITLE
FATAL EXCEPTION

### ISSUE THREAD

**Issue by johnjake** [daimajia/AndroidViewHover#28]
Hey I used API 24 try using API 23 but got this error when I click

FATAL EXCEPTION: main
                                                                                Process: com.example.johnj_000.hovericons, PID: 2881
                                                                                java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v8/renderscript/RenderScript;
                                                                                    at com.daimajia.androidviewhover.tools.Blur.apply(Blur.java:20)
                                                                                    at com.daimajia.androidviewhover.BlurLayout.addBlurImage(BlurLayout.java:182)
                                                                                    at com.daimajia.androidviewhover.BlurLayout.hover(BlurLayout.java:120)
                                                                                    at com.daimajia.androidviewhover.BlurLayout.access$000(BlurLayout.java:29)
                                                                                    at com.daimajia.androidviewhover.BlurLayout$BlurLayoutDetector.onSingleTapUp(BlurLayout.java:98)
                                                                                    at android.view.GestureDetector.onTouchEvent(GestureDetector.java:635)
                                                                                    at com.daimajia.androidviewhover.BlurLayout.onTouchEvent(BlurLayout.java:84)

**Comment by tahafarooqui** [comment]
Same here !! Not working ..

**Comment by johnjake** [comment]
I was able to do it by modifying the lib.
