### ISSUE TITLE
 Error loading RS jni library: java.lang.UnsatisfiedLinkError 

### ISSUE THREAD

**Issue by saurabh-konstant** [daimajia/AndroidViewHover#5]
Getting Error while click on any item in app. 
I have already add the support v8 jar file 

Here is the log .... 

09-01 07:44:19.938: E/RenderScript_jni(15327): Error loading RS jni library: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:   115 cannot locate '__strlen_chk'...
09-01 07:44:19.938: E/InputEventReceiver(15327): Exception dispatching input event.
09-01 07:44:19.938: E/MessageQueue-JNI(15327): Exception in MessageQueue callback: handleReceiveCallback
09-01 07:44:19.946: E/MessageQueue-JNI(15327): android.support.v8.renderscript.RSRuntimeException: Error loading RS jni library: java.lang.UnsatisfiedLinkError: Cannot load library: reloc_library[1306]:   115 cannot locate '__strlen_chk'...
09-01 07:44:19.946: E/MessageQueue-JNI(15327):  at android.support.v8.renderscript.RenderScript.create(RenderScript.java:945)
09-01 07:44:19.946: E/MessageQueue-JNI(15327):  at android.support.v8.renderscript.RenderScript.create(RenderScript.java:982)
09-01 07:44:19.946: E/MessageQueue-JNI(15327):  at android.support.v8.renderscript.RenderScript.create(RenderScript.java:968)

**Comment by Mardoqueu** [comment]
i am having this error: 
Error:(13, 0) Gradle DSL method not found: 'compile()'
Possible causes:<ul><li>The project 'AndroidViewHover-master' may be using a version of Gradle that does not contain the method.
<a href="open.wrapper.file">Open Gradle wrapper file</a></li><li>The build file may be missing a Gradle plugin.
<a href="apply.gradle.plugin">Apply Gradle plugin</a></li>


I don't know where I put the Maven:
<dependency>
        <groupId>com.nineoldandroids</groupId>
        <artifactId......

Help-me, please!!!

**Comment by iampkuhz** [comment]
Build Tools, Revision 23.0.3  fix this bug, I have try and sucess.

http://stackoverflow.com/a/36322996/4856869
